import { alpha } from 'styles/colorUtils';

const palette = {
  INK_5: '#FFFFFF',
  INK_7: '#FCFCFC',
  INK_10: '#F3F4F5',
  INK_20: '#E6E8EB',
  INK_30: '#D2D5D9',
  INK_40: '#B9BFC4',
  INK_50: '#A0A7AD',
  INK_60: '#828990',
  INK_70: '#656C72',
  INK_80: '#545A60',
  INK_90: '#41474D',
  INK_100: '#222529',

  BLUE_5: '#F0F6FA',
  BLUE_7: '#DBEAF5',
  BLUE_10: '#C8DEED',
  BLUE_20: '#A4C8E2',
  BLUE_30: '#7DB2D5',
  BLUE_40: '#5B9DCB',
  BLUE_50: '#4691C7',
  BLUE_70: '#0063be',
  BLUE_80: '#004c9d',
  BLUE_90: '#003f83', // primary color
  BLUE_A10: '#B4E1FA',

  YELLOW_5: '#FFF6DD',
  YELLOW_10: '#FFE6A9',
  YELLOW_30: '#fae55f',
  YELLOW_50: '#ffd500',
  YELLOW_60: '#fdc500',
  YELLOW_70: '#fbb500', // primary color
  YELLOW_90: '#965e00',

  GREEN_10: '#CAEED0',
  GREEN_50: '#4FB75F',
  GREEN_90: '#348540',
  RED_10: '#FFD3D3',
  RED_50: '#E65147',
  RED_90: '#B23F37',
} as const;

export const theme = {
  palette,

  btn_primary_bg: palette.BLUE_90,
  btn_primary_border: palette.BLUE_90,
  btn_primary_color: palette.INK_5,
  btn_primary_hover_bg: palette.BLUE_50,
  btn_primary_hover_border: palette.BLUE_50,
  btn_primary_hover_color: palette.INK_5,
  btn_primary_active_bg: palette.BLUE_90,
  btn_primary_active_border: palette.BLUE_90,
  btn_primary_active_color: palette.INK_5,
  btn_primary_disabled_bg: palette.INK_10,
  btn_primary_disabled_border: palette.INK_30,
  btn_primary_disabled_color: palette.INK_50,

  btn_secondary_bg: palette.INK_5,
  btn_secondary_border: palette.INK_30,
  btn_secondary_color: palette.INK_70,
  btn_secondary_hover_bg: palette.BLUE_7,
  btn_secondary_hover_border: palette.BLUE_70,
  btn_secondary_hover_color: palette.BLUE_70,
  btn_secondary_active_bg: palette.BLUE_A10,
  btn_secondary_active_border: palette.BLUE_70,
  btn_secondary_active_color: palette.BLUE_70,
  btn_secondary_disabled_bg: palette.INK_10,
  btn_secondary_disabled_border: palette.INK_30,
  btn_secondary_disabled_color: palette.INK_50,

  btn_text_bg: 'transparent',
  btn_text_border: 'transparent',
  btn_text_color: palette.INK_80,
  btn_text_hover_bg: 'transparent',
  btn_text_hover_border: 'transparent',
  btn_text_hover_color: palette.BLUE_70,
  btn_text_active_bg: 'transparent',
  btn_text_active_border: 'transparent',
  btn_text_active_color: palette.BLUE_70,
  btn_text_disabled_bg: 'transparent',
  btn_text_disabled_border: 'transparent',
  btn_text_disabled_color: alpha(palette.INK_70, 0.5),

  btn_semantic_bg: palette.INK_5,
  btn_semantic_border: palette.YELLOW_50,
  btn_semantic_color: palette.YELLOW_90,
  btn_semantic_hover_bg: palette.YELLOW_5,
  btn_semantic_hover_border: palette.YELLOW_50,
  btn_semantic_hover_color: palette.YELLOW_90,
  btn_semantic_active_bg: palette.YELLOW_10,
  btn_semantic_active_border: palette.YELLOW_90,
  btn_semantic_active_color: palette.YELLOW_90,
  btn_semantic_disabled_bg: palette.INK_10,
  btn_semantic_disabled_border: palette.INK_30,
  btn_semantic_disabled_color: palette.INK_50,
};
